QA - Frame work
brighthr/progression-framework pull request #18
Opened 2020-12-01 19:25 UTC by Prav-Patel

2020-12-02 15:47 UTC, Paul2e requested changes

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
> +          - "Transparent about mistakes they've made, early informs the people"
```suggestion
          - "Transparent about mistakes they've made, informs relevant people as soon as possible."
```

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
> +        - "Contributes in three Amigos"
Do we call them three amigos or kickoffs?

Be good to be consistent across the ranges if possible.

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
> +          - "Runs show and tells to stake holders"
Bit of an interesting one this. Most of our stakeholders aren't engaged with the team on a daily level, and show and tells are done by PO / Product.

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
> +        - "Lead retros and other team improvement sessions"
I honestly think anyone should be able to do this.

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
>          - "Proactively raises issues they spot in retrospectives"
As below.

2020-12-02 15:47 UTC, Paul2e commented on frameworks/engineering/quality.md
> +          - "Makes pragmatic choices on their testing approach"
This needs to be in BOLD, SIZE 50!

2020-12-02 15:48 UTC, Paul2e commented
@Prav-Patel Mostly there, just a few comments. I'll leave it upto you if you want to make them. 👍

2020-12-02 15:50 UTC, Paul2e commented on package.json
> +    "@babel/polyfill": "^7.12.1",
👍

2020-12-04 22:49 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +          - "Transparent about mistakes they've made, early informs the people"
👨🏽‍🏭 Fixed

2020-12-04 22:53 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +        - "Contributes in three Amigos"
👨🏽‍🏭 Fixed
**Definitions**
**3 Amigos** - Would be for a ticket basis within a feature - BA/QA/DEV/UX. making sure we all clear on what needs to be done.
**Kick Off** - would be the start of a project the Whats, Whys Whos - Any high level designs or requirements shared based on a Problem we need to resolve.

Does that make sense?

2020-12-04 22:56 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +        - "Contributes in three Amigos"
Ahh I see what you are saying here.... 
Shall I update to both to:

"Contributes in Kick Offs"
"Points out improvements in test scenario reviews or in three amigo sessions"

- does that sound better?

2020-12-04 23:01 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +          - "Runs show and tells to stake holders"
We dont have a PO so we have historically ran these sessions with the Dev Lead.
Today for example - Mahmud ran Payroll Navigator to Senior Stakeholders, Last Mukesh did it.
Friday Big Stand- ups also count in this scenario I think. 
They might not need to do it, but if they have the skill to then i think that is warrants merit. Dont you agree?

2020-12-04 23:04 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +        - "Lead retros and other team improvement sessions"
as in all levels? or all disciplines?

2020-12-04 23:04 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +          - "Makes pragmatic choices on their testing approach"
Preach 🙌🏽

2021-01-06 13:58 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +        - "Contributes in three Amigos"
@Paul2e What do you think?

2021-01-06 14:03 UTC, Prav-Patel commented on frameworks/engineering/quality.md
> +        - "Contributes in three Amigos"
I've gone with adding them both.

2021-01-06 17:10 UTC, Paul2e approved these changes

2021-01-07 13:09 UTC, merged