Mobile content revise
brighthr/progression-framework pull request #30
Opened 2021-01-13 10:32 UTC by tonyphn

Revise mobile content to be more inline with other discipline levels.

2021-01-13 12:28 UTC, Prav-Patel commented on frameworks/engineering/mobile.md
> +          - "Fixe simple bugs or issues"
Fix

2021-01-13 12:29 UTC, Prav-Patel commented on frameworks/engineering/mobile.md
> -              - "Understands impact on app performance to use either"
This was right `Understands `

2021-01-13 12:35 UTC, Prav-Patel commented on frameworks/engineering/mobile.md
> +We sort them into six levels, and we try to give specific examples of behaviours we expect for each. Each of those levels has a fairly wide salary range associated with it, and within each level you
There is only 4 levels. 1-4

2021-01-13 12:36 UTC, Prav-Patel commented on frameworks/engineering/mobile.md
> -  - name: "summary"
This was a good idea, why did you remove?

2021-01-13 12:37 UTC, Prav-Patel reviewed
I've made some comments, what made you make every point singular?

2021-01-13 13:52 UTC, tonyphn commented on frameworks/engineering/mobile.md
> -  - name: "summary"
I like it too just haven't found a good summary yet

2021-01-13 13:53 UTC, tonyphn commented on frameworks/engineering/mobile.md
> -              - "Understands impact on app performance to use either"
was meant to refer to you/they here

2021-01-13 13:55 UTC, tonyphn commented on frameworks/engineering/mobile.md
> +We sort them into six levels, and we try to give specific examples of behaviours we expect for each. Each of those levels has a fairly wide salary range associated with it, and within each level you
I think you commented on a outdated change. It is four atm.

2021-01-13 13:57 UTC, tonyphn commented on frameworks/engineering/mobile.md
> +          - "Fixe simple bugs or issues"
Good spot, updated thanks.

2021-01-13 13:59 UTC, tonyphn commented
> I've made some comments, what made you make every point singular?

There are still some points with examples. I only made some simple/obvious points singular.

2021-01-13 15:00 UTC, LazyDave76 requested changes
some spelling errors have crept in.  you seem to dislike the letter s :)

2021-01-13 16:51 UTC, Prav-Patel approved these changes

2021-01-14 09:25 UTC, tonyphn commented on frameworks/engineering/mobile.md
> +              - "Researche potential solutions and evaluates how they solve the problem."
Nice spots updated thanks @LazyDave76

2021-01-14 09:27 UTC, LazyDave76 approved these changes

2021-01-14 10:15 UTC, merged